version: '3.7'
services:
  hasura:
    image: hasura/graphql-engine:v1.0.0-beta.10.cli-migrations
    ports:
      - "8090:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:postgres@postgres:5432/cexplorer
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup, http-log, webhook-log, websocket-log, query-log
    volumes:
      - ../hasura/migrations:/hasura-migrations
  postgres:
    image: postgres:11.5-alpine
    restart: always
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cexplorer
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ../test/postgres/init:/docker-entrypoint-initdb.d
