version: "3.8"

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command: -p ${POSTGRES_PORT}
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    shm_size: '2gb'
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  mithril:
    build:
      context: ./
      dockerfile: ./dockerfiles/mithril/Dockerfile
      args: 
        MITHRIL_VERSION: ${MITHRIL_VERSION}
    environment:
      - NETWORK=${NETWORK}
      - MITHRIL_SYNC=${MITHRIL_SYNC}
      - SNAPSHOT_DIGEST=${SNAPSHOT_DIGEST}
      - AGGREGATOR_ENDPOINT=${AGGREGATOR_ENDPOINT}
      - GENESIS_VERIFICATION_KEY=${GENESIS_VERIFICATION_KEY}
      - ANCILLARY_VERIFICATION_KEY=${ANCILLARY_VERIFICATION_KEY}
    volumes:
      - ${CARDANO_NODE_DB}:/node/db

  cardano-node:
    image: cardanofoundation/cardano-graphql-cardano-node:${CARDANO_NODE_VERSION}
    build:
      context: ./
      dockerfile: ./dockerfiles/cardano-node/Dockerfile
      args:
        CARDANO_NODE_VERSION: ${CARDANO_NODE_VERSION}
    environment:
      - NETWORK=${NETWORK}
      - CARDANO_NODE_PORT=${CARDANO_NODE_PORT}
    volumes:
      - ${CARDANO_NODE_DIR}:/ipc
      - ${CARDANO_NODE_DB}:/node/db
    restart: unless-stopped
    entrypoint: ["/sbin/entrypoint.sh", "cardano-node"]
    ports:
      - ${CARDANO_NODE_PORT}:${CARDANO_NODE_PORT}
    depends_on:
      mithril:
        condition: service_completed_successfully

  cardano-submit-api:
    image: cardanofoundation/cardano-graphql-cardano-node:${CARDANO_NODE_VERSION}
    environment:
      - NETWORK=${NETWORK}
    volumes:
      - ${CARDANO_NODE_DIR}:/ipc
    restart: unless-stopped
    entrypoint: ["/sbin/entrypoint.sh", "cardano-submit-api"]
    ports:
      - ${CARDANO_SUBMIT_API_PORT}:8090
    depends_on:
      - cardano-node

  cardano-db-sync:
    platform: linux/x86_64
    image: ghcr.io/intersectmbo/cardano-db-sync:${CARDANO_DB_SYNC_VERSION}
    command: [ "--config", "/config/cardano-db-sync/config.json", "--socket-path", "/node-ipc/node.socket" ]
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - RESTORE_SNAPSHOT=${RESTORE_SNAPSHOT}
      - RESTORE_RECREATE_DB=N
    depends_on:
      # Depend on both services to be started before starting.
      cardano-node:
        condition: service_started
      postgres:
        condition: service_started
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - ./config/network/${NETWORK}:/config
      - ${CARDANO_DB_SYNC_DIR}:/var/lib/cexplorer
      - ${CARDANO_NODE_DIR}:/node-ipc
    restart: on-failure
    stop_signal: SIGINT
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  hasura:
    build:
      context: ./packages/api-cardano-db-hasura/hasura
    image: cardanofoundation/cardano-graphql-hasura:${CARDANO_GRAPHQL_VERSION}
    ports:
      - ${HASURA_PORT}:8080
    depends_on:
      - "postgres"
    restart: unless-stopped
    environment:
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_CORS_DOMAIN=http://localhost:9695
      - POSTGRES_PORT=${POSTGRES_PORT}
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  hasura-setup:
    build:
      context: .
      target: background
    image: cardanofoundation/cardano-graphql-background:${CARDANO_GRAPHQL_VERSION}
    command: ["node", "setup.js"]
    depends_on:
      hasura:
        condition: service_healthy
    restart: "no"
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    environment:
      - LOGGER_MIN_SEVERITY=${LOGGER_MIN_SEVERITY}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  background:
    build:
      context: .
      target: background
    image: cardanofoundation/cardano-graphql-background:${CARDANO_GRAPHQL_VERSION}
    depends_on:
      hasura-setup:
        condition: service_completed_successfully
      postgres:
        condition: service_started
    environment:
      - COMPOSE_PROFILES=${COMPOSE_PROFILES}
      - LOGGER_MIN_SEVERITY=${LOGGER_MIN_SEVERITY}
      - METADATA_SERVER_URI=${METADATA_SERVER_URI}
      - POSTGRES_PORT=${POSTGRES_PORT}
    restart: on-failure
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  server:
    platform: linux/x86_64
    build:
      context: .
      target: server
    image: cardanofoundation/cardano-graphql-server:${CARDANO_GRAPHQL_VERSION}
    environment:
      - ALLOW_INTROSPECTION=true
      - CACHE_ENABLED=true
      - CARDANO_NODE_CONFIG_PATH=/config/network/${NETWORK}/cardano-node/config.json
      - CARDANO_NODE_PROMETHEUS_HOST=cardano-node
      - CARDANO_NODE_PROMETHEUS_PORT=12798
      - CARDANO_SUBMIT_API_HOST=cardano-submit-api
      - LOGGER_MIN_SEVERITY=${LOGGER_MIN_SEVERITY}
      - NETWORK=${NETWORK}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      cardano-submit-api:
        condition: service_started
      hasura:
        condition: service_healthy
      hasura-setup:
        condition: service_completed_successfully
    expose:
      - ${API_PORT}
    ports:
      - ${API_PORT}:3100
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  token-metadata-registry:
    image: cardanofoundation/cf-token-metadata-registry-api:${TOKEN_REGISTRY_VERSION}
    profiles: ["token-registry"]
    volumes:
      - ./scripts/:/app/scripts/:ro
    entrypoint: ["sh", "/app/scripts/token-registry-init.sh"]
    ports:
      - ${TOKEN_REGISTRY_PORT}:8080
    environment:
      - TOKEN_METADATA_SYNC_JOB=true
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=postgres
      - DB_SCHEMA=tokenregistry
      - NETWORK=${NETWORK}
      - CARDANO_NODE_HOST=${CARDANO_NODE_HOST}
      - CARDANO_NODE_PORT=${CARDANO_NODE_PORT}
      - CIP_QUERY_PRYORITY=${CARDANO_NODE_PORT}
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    restart: on-failure
    depends_on:
      - postgres

  index-service:
    build:
      context: ./packages/index-service
      dockerfile: Dockerfile
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    profiles: ["indexes"]
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - MIN_BLOCK_COUNT=${INDEX_MIN_BLOCK_COUNT:-1000}
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    depends_on:
      cardano-db-sync:
        condition: service_started
      postgres:
        condition: service_started
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "10"

secrets:
  postgres_db:
    file: ./placeholder-secrets/postgres_db
  postgres_password:
    file: ./placeholder-secrets/postgres_password
  postgres_user:
    file: ./placeholder-secrets/postgres_user
volumes:
  db-sync-data:
  node-db:
  node-ipc:
  postgres14-data:
