#!/usr/bin/env bash

set -e
# Unofficial bash strict mode.
# See: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -u
set -o pipefail

here="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd)"
root_path="$(cd "$here/.." && pwd)"
cd "$root_path"

export PATH=$PWD/bin:$PATH

source ./scripts/nodes-configuration.sh

UNAME=$(uname -s) SED=
case $UNAME in
  Darwin )      SED="gsed";;
  Linux )       SED="sed";;
esac

case $(uname) in
Darwin) date='gdate' ;;
*) date='date' ;;
esac
timeISO=$($date -d "now + 30 seconds" -u +"%Y-%m-%dT%H:%M:%SZ")
timeUnix=$($date -d "now + 30 seconds" -u +%s)

sprocket() {
  if [ "$UNAME" == "Windows_NT" ]; then
    # Named pipes names on Windows must have the structure: "\\.\pipe\PipeName"
    # See https://docs.microsoft.com/en-us/windows/win32/ipc/pipe-names
    echo -n '\\.\pipe\'
    echo "$1" | sed 's|/|\\|g'
  else
    echo "$1"
  fi
}

UNAME=$(uname -s) DATE=
case $UNAME in
  Darwin )      DATE="gdate";;
  Linux )       DATE="date";;
  MINGW64_NT* ) UNAME="Windows_NT"
                DATE="date";;
esac

NETWORK_MAGIC=888
SECURITY_PARAM=10
INIT_SUPPLY=10020000012
MAX_SUPPLY=45000000000000000
START_TIME="$(${DATE} -d "now + 30 seconds" +%s)"
ROOT=network-files

if test -d "${ROOT}/byron-gen-command"; then
  echo  "Existing \"${ROOT}/byron-gen-command\" directory will be deleted"
  rm -rf "${ROOT}/byron-gen-command"
fi

mkdir -p "${ROOT}"

cat > "${ROOT}/byron.genesis.spec.json" <<EOF
{
  "heavyDelThd":     "300000000000",
  "maxBlockSize":    "2000000",
  "maxTxSize":       "4096",
  "maxHeaderSize":   "2000000",
  "maxProposalSize": "700",
  "mpcThd": "20000000000000",
  "scriptVersion": 0,
  "slotDuration": "1000",
  "softforkRule": {
    "initThd": "900000000000000",
    "minThd": "600000000000000",
    "thdDecrement": "50000000000000"
  },
  "txFeePolicy": {
    "multiplier": "43946000000",
    "summand": "155381000000000"
  },
  "unlockStakeEpoch": "18446744073709551615",
  "updateImplicit": "10000",
  "updateProposalThd": "100000000000000",
  "updateVoteThd": "1000000000000"
}
EOF

cardano-cli byron genesis genesis \
  --protocol-magic ${NETWORK_MAGIC} \
  --start-time "${START_TIME}" \
  --k "${SECURITY_PARAM}" \
  --n-poor-addresses 0 \
  --n-delegate-addresses "${NUM_SP_NODES}" \
  --total-balance ${INIT_SUPPLY} \
  --delegate-share 1 \
  --avvm-entry-count 0 \
  --avvm-entry-balance 0 \
  --protocol-parameters-file "${ROOT}/byron.genesis.spec.json" \
  --genesis-output-dir "${ROOT}/byron-gen-command"

# Because in Babbage the overlay schedule and decentralization parameter
# are deprecated, we must use the "create-staked" cli command to create
# SPs in the ShelleyGenesis

cp templates/babbage/alonzo-babbage-test-genesis.json "${ROOT}/genesis.alonzo.spec.json"
cp templates/babbage/byron-configuration.yaml "${ROOT}/configuration.yaml"

$SED -i "${ROOT}/configuration.yaml" \
     -e 's/Protocol: RealPBFT/Protocol: Cardano/' \
     -e 's|GenesisFile: genesis.json|ByronGenesisFile: genesis/byron/genesis.json|' \
     -e '/ByronGenesisFile/ aShelleyGenesisFile: genesis/shelley/genesis.json' \
     -e '/ByronGenesisFile/ aAlonzoGenesisFile: genesis/shelley/genesis.alonzo.json' \
     -e 's/RequiresNoMagic/RequiresMagic/' \
     -e 's/LastKnownBlockVersion-Major: 0/LastKnownBlockVersion-Major: 6/' \
     -e 's/LastKnownBlockVersion-Minor: 2/LastKnownBlockVersion-Minor: 0/'

  echo "" >> "${ROOT}/configuration.yaml"
  echo "PBftSignatureThreshold: 0.6" >> "${ROOT}/configuration.yaml"
  echo "" >> "${ROOT}/configuration.yaml"

  echo "TestShelleyHardForkAtEpoch: 0" >> "${ROOT}/configuration.yaml"
  echo "TestAllegraHardForkAtEpoch: 0" >> "${ROOT}/configuration.yaml"
  echo "TestMaryHardForkAtEpoch: 0" >> "${ROOT}/configuration.yaml"
  echo "TestAlonzoHardForkAtEpoch: 0" >> "${ROOT}/configuration.yaml"
  echo "TestBabbageHardForkAtEpoch: 0" >> "${ROOT}/configuration.yaml"
  echo "TestEnableDevelopmentNetworkProtocols: True" >> "${ROOT}/configuration.yaml"

# Copy the cost mode
cardano-cli genesis create-staked --genesis-dir "${ROOT}" \
  --testnet-magic "${NETWORK_MAGIC}" \
  --gen-pools ${NUM_SP_NODES} \
  --supply ${MAX_SUPPLY} \
  --supply-delegated ${MAX_SUPPLY} \
  --gen-stake-delegs ${NUM_SP_NODES} \
  --gen-utxo-keys ${NUM_SP_NODES}

# create the node directories
for NODE in ${SP_NODES}; do
  mkdir -p "${ROOT}/${NODE}"
done

# Here we move all of the keys etc generated by create-staked
# for the nodes to use

# Move all genesis related files
mkdir -p "${ROOT}/genesis/byron"
mkdir -p "${ROOT}/genesis/shelley"

mv "${ROOT}/byron-gen-command/genesis.json" "${ROOT}/genesis/byron/genesis-wrong.json"
mv "${ROOT}/genesis.alonzo.json" "${ROOT}/genesis/shelley/genesis.alonzo.json"
mv "${ROOT}/genesis.json" "${ROOT}/genesis/shelley/genesis.json"

jq --raw-output ".protocolConsts.protocolMagic = ${NETWORK_MAGIC}" "${ROOT}/genesis/byron/genesis-wrong.json" > "${ROOT}/genesis/byron/genesis.json"

rm "${ROOT}/genesis/byron/genesis-wrong.json"


$SED -i "${ROOT}/genesis/shelley/genesis.json" \
    -e 's/"slotLength": 1/"slotLength": 0.2/' \
    -e 's/"activeSlotsCoeff": 5.0e-2/"activeSlotsCoeff": 0.1/' \
    -e 's/"securityParam": 2160/"securityParam": 10/' \
    -e 's/"epochLength": 432000/"epochLength": 1000/' \
    -e "s/\"maxLovelaceSupply\": 0/\"maxLovelaceSupply\": ${MAX_SUPPLY}/" \
    -e 's/"minFeeA": 1/"minFeeA": 44/' \
    -e 's/"minFeeB": 0/"minFeeB": 155381/' \
    -e 's/"minUTxOValue": 0/"minUTxOValue": 1000000/' \
    -e 's/"decentralisationParam": 1.0/"decentralisationParam": 0.7/' \
    -e 's/"major": 0/"major": 7/' \
    -e 's/"rho": 0.0/"rho": 0.1/' \
    -e 's/"tau": 0.0/"tau": 0.1/' \
    -e 's/"updateQuorum": 5/"updateQuorum": 2/'

for NODE_ID in ${SP_NODES_ID}; do
  TARGET="${ROOT}/node-sp${NODE_ID}"
  PORT="$(("$NODE_ID" + 3000))"

  mv "${ROOT}/pools/vrf${NODE_ID}.skey" "${TARGET}/vrf.skey"
  mv "${ROOT}/pools/opcert${NODE_ID}.cert" "${TARGET}/opcert.cert"
  mv "${ROOT}/pools/kes${NODE_ID}.skey" "${TARGET}/kes.skey"

  BYRON_KEYS_POSFIX=$(seq -f '%03.f' $(("$NODE_ID" - 1)) $(("$NODE_ID" - 1)))
  #Byron related
  mv "${ROOT}/byron-gen-command/delegate-keys.${BYRON_KEYS_POSFIX}.key" "${TARGET}/byron-delegate.key"
  mv "${ROOT}/byron-gen-command/delegation-cert.${BYRON_KEYS_POSFIX}.json" "${TARGET}/byron-delegation.cert"

  echo "${PORT}" > "${TARGET}/port"

done

# Make topology files
for ID in ${SP_NODES_ID}; do
  port="$(("$ID" + 3001))"

  if [ "$ID" -ge "$(("$NUM_SP_NODES" - 1))" ] # Wrap around
  then
    port="$(("$port" - "$(("$NUM_SP_NODES" - 1))"))"
  fi

  secondPort="$(("$port" + 1))"

  cat > "${ROOT}/node-sp${ID}/topology.json" <<EOF
  {
     "Producers": [
       {
         "addr": "127.0.0.1",
         "port": ${port},
         "valency": 1
       }
     , {
         "addr": "127.0.0.1",
         "port": ${secondPort},
         "valency": 1
       }
     ]
   }
EOF

done

for NODE in ${SP_NODES}; do
  (
    echo "#!/usr/bin/env bash"
    echo ""
    echo "export PATH=\$PWD/bin:\$PATH"
    echo ""
    echo "cardano-node run \\"
    echo "  --config                          '${ROOT}/configuration.yaml' \\"
    echo "  --topology                        '${ROOT}/${NODE}/topology.json' \\"
    echo "  --database-path                   '${ROOT}/${NODE}/db' \\"
    echo "  --socket-path                     '$(sprocket "${ROOT}/${NODE}/node.sock")' \\"
    echo "  --shelley-kes-key                 '${ROOT}/${NODE}/kes.skey' \\"
    echo "  --shelley-vrf-key                 '${ROOT}/${NODE}/vrf.skey' \\"
    echo "  --byron-delegation-certificate    '${ROOT}/${NODE}/byron-delegation.cert' \\"
    echo "  --byron-signing-key               '${ROOT}/${NODE}/byron-delegate.key' \\"
    echo "  --shelley-operational-certificate '${ROOT}/${NODE}/opcert.cert' \\"
    echo "  --port                            $(cat "${ROOT}/${NODE}/port") \\"
    echo "  | tee -a '${ROOT}/${NODE}/node.log'"
    echo ""
    echo "wait"
  ) > "${ROOT}/${NODE}.sh"

  chmod a+x "${ROOT}/${NODE}.sh"

  echo "${ROOT}/${NODE}.sh"
done

echo "Update start time in genesis files"
$SED -i -E "s/\"startTime\": [0-9]+/\"startTime\": ${timeUnix}/" ${ROOT}/genesis/byron/genesis.json
$SED -i -E "s/\"systemStart\": \".*\"/\"systemStart\": \"${timeISO}\"/" ${ROOT}/genesis/shelley/genesis.json

byronGenesisHash=$(cardano-cli byron genesis print-genesis-hash --genesis-json ${ROOT}/genesis/byron/genesis.json)
shelleyGenesisHash=$(cardano-cli genesis hash --genesis ${ROOT}/genesis/shelley/genesis.json)
alonzoGenesisHash=$(cardano-cli genesis hash --genesis ${ROOT}/genesis/shelley/genesis.alonzo.json)

echo "Byron genesis hash: $byronGenesisHash"
echo "Shelley genesis hash: $shelleyGenesisHash"
echo "Alonzo genesis hash: $alonzoGenesisHash"

$SED -i -E "s/ByronGenesisHash: \".*\"/ByronGenesisHash: \"${byronGenesisHash}\"/"  ${ROOT}/configuration.yaml
$SED -i -E "s/ShelleyGenesisHash: \".*\"/ShelleyGenesisHash: \"${shelleyGenesisHash}\"/"  ${ROOT}/configuration.yaml
$SED -i -E "s/AlonzoGenesisHash: \".*\"/AlonzoGenesisHash: \"${alonzoGenesisHash}\"/"  ${ROOT}/configuration.yaml

# Create config folder
rm -rf ./config/*
mkdir -p ./config/network/cardano-db-sync/
mkdir -p ./config/network/cardano-db-sync/
mkdir -p ./config/network/cardano-node/genesis/
mkdir -p ./config/network/genesis/

cp ./templates/babbage/db-sync-config.json ./config/network/cardano-db-sync/config.json
cp ./templates/babbage/node-config.json ./config/network/cardano-node/config.json

$SED -i -E "s/\"ByronGenesisHash\": \".*\"/\"ByronGenesisHash\": \"${byronGenesisHash}\"/" ./config/network/cardano-node/config.json
$SED -i -E "s/\"ShelleyGenesisHash\": \".*\"/\"ShelleyGenesisHash\": \"${shelleyGenesisHash}\"/" ./config/network/cardano-node/config.json
$SED -i -E "s/\"AlonzoGenesisHash\": \".*\"/\"AlonzoGenesisHash\": \"${alonzoGenesisHash}\"/" ./config/network/cardano-node/config.json

cp ./templates/babbage/topology.json ./config/network/cardano-node/topology.json
# docker hostname in topology.json isn't working, so need to specify ip of local network
CONTAINER_IP=$(hostname -I | xargs)
$SED -i "s/172.17.0.1/$CONTAINER_IP/g" ./config/network/cardano-node/topology.json

cp "${ROOT}"/genesis/byron/genesis.json ./config/network/cardano-node/genesis/byron.json
cp "${ROOT}"/genesis/byron/genesis.json ./config/network/genesis/byron.json

cp "${ROOT}"/genesis/shelley/genesis.json ./config/network/cardano-node/genesis/shelley.json
cp "${ROOT}"/genesis/shelley/genesis.json ./config/network/genesis/shelley.json

cp "${ROOT}"/genesis/shelley/genesis.alonzo.json ./config/network/cardano-node/genesis/alonzo.json
cp "${ROOT}"/genesis/shelley/genesis.alonzo.json ./config/network/genesis/alonzo.json

mkdir -p "${ROOT}/run"

echo "#!/usr/bin/env bash" > "${ROOT}/run/all.sh"
echo "" >> "${ROOT}/run/all.sh"
echo "" >> "${ROOT}/run/all.sh"
echo "export PATH=\$PWD/bin:\$PATH" >> "${ROOT}/run/all.sh"
echo "" >> "${ROOT}/run/all.sh"

for NODE in ${SP_NODES}; do
  echo "$ROOT/${NODE}.sh &" >> "${ROOT}/run/all.sh"
done
echo "" >> "${ROOT}/run/all.sh"
echo "wait" >> "${ROOT}/run/all.sh"

chmod a+x "${ROOT}/run/all.sh"

wait
