DROP VIEW IF EXISTS
  "AdaPots",
  "ActiveStake",
  "Block",
  "Cardano",
  "Collateral",
  "Delegation",
  "Epoch",
  "ProtocolParams",
  "Redeemer",
  "Reward",
  "Script",
  "SlotLeader",
  "StakeDeregistration",
  "StakePool",
  "StakePoolOwner",
  "StakeRegistration",
  "StakePoolRetirement",
  "TokenMint",
  "TokenInOutput",
  "Transaction",
  "TransactionInput",
  "TransactionOutput",
  "Utxo",
  "Withdrawal" CASCADE;
