query outputsByCredentials(
  $hash: Hash32Hex!
  $paymentCredential: Hash28Hex!
  $owner: StakeAddress!
  $nonOwner: StakeAddress!
) {
  transaction: transactions(
    where: { hash: { _eq: $hash } }
  ) {
    hash
    outputs(order_by: { index: asc }) {
      index
      paymentCredential
      stakeAddress
      value
      tokens {
        quantity
        asset {
          policyId
          assetName
        }
      }
    }
  }
  heldByOwner: transactions(
    where: {
      hash: { _eq: $hash }
      outputs: {
        paymentCredential: { _eq: $paymentCredential }
        stakeAddress: { _eq: $owner }
      }
    }
  ) {
    hash
  }
  notHeldByNonOwner: transactions(
    where: {
      hash: { _eq: $hash }
      outputs: {
        paymentCredential: { _eq: $paymentCredential }
        stakeAddress: { _eq: $nonOwner }
      }
    }
  ) {
    hash
  }
}
